### ISSUE TITLE
Only takes IP

### ISSUE THREAD

**Issue by RandomSignals** [Ebryx/Nessus_Map#32]
Importing Nessus file only outputs host as IP and URLs are not included. Is this intended behavior?

**Comment by Anon-Exploiter** [comment]
I think it may be because you didn't enable the scan configurations in Nessus which displays hostnames instead of IPs of the targets. When you added the scan, did you feed hostnames or IPs? 

Checkout the second option:
https://docs.tenable.com/nessus/Content/ReportSettings.htm#Output

![image](https://github.com/Ebryx/Nessus_Map/assets/18597330/835e02a4-d8ec-4c74-bde8-936c8ea0f951)

**Comment by DuckSound0** [comment]
I feeded the Nessus file that included targets in IP and hostnames, so Nessus scan displays both. Sorry for late response.
